/*
SELECT C.AUTHOR_ID, C.AUTHOR_NAME, C.CATEGORY, C.PRICE*D.SALES AS TOTAL_SALES
FROM (
        SELECT A.BOOK_ID ,B.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE) PRICE
    FROM BOOK A JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
    GROUP BY AUTHOR_NAME, CATEGORY
) C
    JOIN
    (
        SELECT BOOK_ID, SALES_DATE, SUM(SALES) SALES
        FROM BOOK_SALES
        WHERE SALES_DATE LIKE '2022-01-%'
        GROUP BY BOOK_ID
    ) D
    ON C.BOOK_ID = D.BOOK_ID
ORDER BY C.AUTHOR_ID, C.CATEGORY DESC
*/

# 도서ID별 가격이 다르다는걸 망각함
SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE*C.SALES) TOTAL_SALES
FROM BOOK A JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID 
    JOIN BOOK_SALES C ON A.BOOK_ID = C.BOOK_ID
WHERE C.SALES_DATE LIKE '2022-01-%'
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC 


/*
AUTHOR_ID   AUTHOR_NAME CATEGORY    TOTAL_SALES
1   홍길동   인문  561000
1   홍길동   경제  1107000
2   김영호   소설  450000
3   김수진   생활  817000
3   김수진   기술  1523000
*/
