SELECT DISTINCT A.CAR_ID, A.CAR_TYPE, FLOOR(A.DAILY_FEE*30*(100-C.DISCOUNT_RATE)/100) AS FEE
FROM (
    SELECT X.CAR_ID, Y.CAR_TYPE, Y.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY X INNER JOIN CAR_RENTAL_COMPANY_CAR Y
    ON X.CAR_ID = Y.CAR_ID AND Y.CAR_TYPE IN ('세단', 'SUV')
    WHERE X.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')
    ) A
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C 
ON A.CAR_TYPE = C.CAR_TYPE AND DURATION_TYPE = '30일 이상'
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC
