
SELECT A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE*30*(1-(B.DISCOUNT_RATE/100))) FEE
FROM (SELECT CAR_ID, CAR_TYPE, DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE IN ('SUV', '세단')
AND CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
)) A
JOIN
(SELECT CAR_TYPE, DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE CAR_TYPE IN ('SUV', '세단') AND DURATION_TYPE = '30일 이상'
 ) B
ON A.CAR_TYPE = B.CAR_TYPE
WHERE  ROUND(A.DAILY_FEE*30*(1-(B.DISCOUNT_RATE/100))) BETWEEN 500000 AND 2000000
ORDER BY  ROUND(A.DAILY_FEE*30*(1-(B.DISCOUNT_RATE/100))) DESC, A.CAR_TYPE, A.CAR_ID

/*
CAR_ID CAR_TYPE FEE
3 세단 1518000
23 세단 1380000
*/
