SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM (
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
    FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME NOT LIKE 'Intact%'
)A INNER JOIN (
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE 'Intact%'
) B ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY ANIMAL_ID