-- 코드를 입력하세요
SELECT YEAR(A.SALES_DATE) YEAR, MONTH(A.SALES_DATE) MONTH, B.GENDER GENDER, COUNT(DISTINCT A.USER_ID) USERS
#A.USER_ID, B.GENDER, A.SALES_DATE
FROM ONLINE_SALE A INNER JOIN (
    SELECT *
    FROM USER_INFO
    WHERE GENDER IS NOT NULL
) B ON A.USER_ID = B.USER_ID
GROUP BY YEAR(A.SALES_DATE), MONTH(A.SALES_DATE), B.GENDER
ORDER BY YEAR, MONTH, GENDER
