SELECT YEAR(A.SALES_DATE) YEAR, MONTH(A.SALES_DATE) MONTH, COUNT(DISTINCT A.USER_ID) AS PUCHASED_USERS, ROUND((COUNT(DISTINCT A.USER_ID)/C.CNT), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE A JOIN USER_INFO B
ON A.USER_ID = B.USER_ID JOIN (
    SELECT COUNT(*) CNT
    FROM USER_INFO
    WHERE JOINED LIKE '2021-%'
) C
WHERE A.USER_ID IN(
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED LIKE '2021-%'
)
GROUP BY YEAR(A.SALES_DATE), MONTH(A.SALES_DATE)
ORDER BY YEAR, MONTH