SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, COUNT(DISTINCT USER_ID) PUCHASED_USERS, ROUND((COUNT(DISTINCT USER_ID) / TOTAL_COUNT), 1) AS PUCHASED_RATIO
FROM (
    SELECT B.ONLINE_SALE_ID, A.USER_ID, B.PRODUCT_ID, B.SALES_AMOUNT, B.SALES_DATE, A.TOTAL_COUNT
    FROM ONLINE_SALE B INNER JOIN (
        SELECT USER_ID, COUNT(*) OVER() AS TOTAL_COUNT
        FROM USER_INFO
        WHERE JOINED LIKE '2021-%'
    ) A ON A.USER_ID = B.USER_ID
) C
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH