SELECT A.PRODUCT_ID, B.PRODUCT_NAME, A.AMOUNT*B.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT B JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE LIKE '2022-05-%'
    GROUP BY PRODUCT_ID
) A
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID