SELECT A.PRODUCT_ID, B.PRODUCT_NAME, (A.AMOUNT*B.PRICE) AS TOTAL_SALES
FROM (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE LIKE '2022-05-%'
    GROUP BY PRODUCT_ID
)A INNER JOIN FOOD_PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID