/*
SELECT C.HISTORY_ID, FLOOR(C.DAY*C.DAILY_FEE*(100-D.DISCOUNT_RATE)/100) AS FEE
FROM (
    SELECT A.HISTORY_ID, B.DAILY_FEE, B.CAR_TYPE, DATEDIFF(A.END_DATE, A.START_DATE)+1 DAY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A INNER JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
    WHERE B.CAR_TYPE = '트럭'
) C INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON (C.CAR_TYPE = D.CAR_TYPE AND C.DAY >= 90 AND D.DURATION_TYPE = '90일 이상') OR
(C.CAR_TYPE = D.CAR_TYPE AND C.DAY < 90 AND C.DAY >= 30 AND D.DURATION_TYPE = '30일 이상') OR
(C.CAR_TYPE = D.CAR_TYPE AND C.DAY < 30 AND C.DAY >= 7 AND D.DURATION_TYPE = '7일 이상')
ORDER BY FEE DESC, C.HISTORY_ID DESC
*/

SELECT C.HISTORY_ID, CASE WHEN C.DAY >= 7 THEN FLOOR(C.DAY*C.DAILY_FEE*(100-D.DISCOUNT_RATE)/100)
ELSE FLOOR(C.DAY*C.DAILY_FEE)
END FEE
FROM (
    SELECT A.HISTORY_ID, B.DAILY_FEE, B.CAR_TYPE, DATEDIFF(A.END_DATE, A.START_DATE)+1 DAY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A INNER JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
    WHERE B.CAR_TYPE = '트럭'
) C 

LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON (C.CAR_TYPE = D.CAR_TYPE AND C.DAY >= 90 AND D.DURATION_TYPE = '90일 이상') OR
(C.CAR_TYPE = D.CAR_TYPE AND C.DAY < 90 AND C.DAY >= 30 AND D.DURATION_TYPE = '30일 이상') OR
(C.CAR_TYPE = D.CAR_TYPE AND C.DAY < 30 AND C.DAY >= 7 AND D.DURATION_TYPE = '7일 이상')
ORDER BY FEE DESC, C.HISTORY_ID DESC