SELECT A.APNT_NO, B.PT_NAME, B.PT_NO, C.MCDP_CD, C.DR_NAME, A.APNT_YMD
FROM (
    SELECT *
    FROM APPOINTMENT
    WHERE APNT_CNCL_YMD IS NULL AND APNT_YMD LIKE '2022-04-13%' AND MCDP_CD = 'CS'
) A JOIN PATIENT B JOIN DOCTOR C
ON A.PT_NO = B.PT_NO AND A.MDDR_ID = C.DR_ID
ORDER BY APNT_YMD