-- 코드를 입력하세요
SELECT A.HOUR HOUR, IF(ANIMAL_ID IS NULL, 0, COUNT(*)) AS COUNT
FROM (
    SELECT (ROW_NUMBER() OVER() -1) AS HOUR
    FROM ANIMAL_OUTS
    LIMIT 24
) A LEFT JOIN ANIMAL_OUTS B
    ON A.HOUR = HOUR(B.DATETIME)
GROUP BY A.HOUR

