-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') DATE_OFBIRTH
from MEMBER_PROFILE
where DATE_OF_BIRTH LIKE '%-03-%' AND GENDER = 'W' AND TLNO <> 'NULL'
order by MEMBER_ID