SELECT A.USER_ID, A.NICKNAME, B.PRICE TOTAL_SALES 
FROM USED_GOODS_USER A JOIN (
    SELECT WRITER_ID, SUM(PRICE) PRICE
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING PRICE >= 700000
) B ON A.USER_ID = B.WRITER_ID
ORDER BY TOTAL_SALES