SELECT A.EMP_NO, A.EMP_NAME, 
CASE 
    WHEN B.SCORE < 80 THEN 'C'
    WHEN B.SCORE < 90 THEN 'B'
    WHEN B.SCORE < 96 THEN 'A'
    ELSE 'S'
END GRADE,
CASE 
    WHEN B.SCORE < 80 THEN 0
    WHEN B.SCORE < 90 THEN A.SAL*0.1
    WHEN B.SCORE < 96 THEN A.SAL*0.15
    ELSE A.SAL*0.2
END BONUS
FROM HR_EMPLOYEES A JOIN (
    SELECT EMP_NO, AVG(SCORE) SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
) B ON A.EMP_NO = B.EMP_NO
ORDER BY A.EMP_NO