SELECT D.MEMBER_NAME, C.REVIEW_TEXT, DATE_FORMAT(C.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW C INNER JOIN (
    SELECT B.MEMBER_NAME, A.MEMBER_ID
    FROM (
        SELECT MEMBER_ID, SUM(REVIEW_SCORE) SCORE
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY SCORE DESC
        LIMIT 1
    ) A INNER JOIN MEMBER_PROFILE B ON A.MEMBER_ID=B.MEMBER_ID
) D ON C.MEMBER_ID = D.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT