SELECT A.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_TREE A JOIN ITEM_INFO B JOIN ITEM_INFO C ON
A.PARENT_ITEM_ID = B.ITEM_ID AND
A.ITEM_ID = C.ITEM_ID
WHERE B.RARITY = 'RARE'
ORDER BY A.ITEM_ID DESC


# SELECT C.ITEM_ID, D.ITEM_NAME, D.RARITY
# FROM (
#     SELECT A.ITEM_ID, B.ITEM_NAME, B.RARITY
#     FROM ITEM_TREE A INNER JOIN (
#         SELECT *
#         FROM ITEM_INFO
#         WHERE RARITY = 'RARE'
# ) B ON A.PARENT_ITEM_ID = B.ITEM_ID ) C INNER JOIN ITEM_INFO D ON C.ITEM_ID = D.ITEM_ID
# ORDER BY C.ITEM_ID DESC