SELECT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
FROM DEVELOPERS A
WHERE EXISTS (
    SELECT *
    FROM SKILLCODES B
    WHERE A.SKILL_CODE & B.CODE = B.CODE AND B.NAME IN ('Python', 'C#')
)
ORDER BY A.ID