SELECT DISTINCT A.CAR_ID CAR_ID
FROM (
    SELECT *
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE LIKE '%-10-%'
) A JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
WHERE B.CAR_TYPE = '세단'
ORDER BY A.CAR_ID DESC
