SELECT CONCAT('/home/grep/src/', B.BOARD_ID, '/', A.FILE_ID, A.FILE_NAME, A.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE A INNER JOIN (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
) B ON A.BOARD_ID = B.BOARD_ID
ORDER BY A.FILE_ID DESC