SELECT A.CATEGORY, A.PRICE MAX_PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT A JOIN 
(
    SELECT CATEGORY, MAX(PRICE) PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) B
ON A.CATEGORY = B.CATEGORY AND A.PRICE = B.PRICE
ORDER BY MAX_PRICE DESC

# 맛있는허니버터칩	CD_CK00003	과자	1950
# 맛있는김치찌개	CD_SU00004	국	2900
# 맛있는배추김치	CD_KC00001	김치	19000
# 맛있는마조유	CD_OL00004	식용유	8950